name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.2.3'
      SERVERPOD_PASSWORD_database: '39ztvhGQ5i2KBcKmfaWrj9N4nV_oxYn4'
      SERVERPOD_PASSWORD_redis: 'S-oaT9LLnRM9fO4J4RCuVPFNuqCr2Gtw'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: focus_butler_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: focus_butler_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: focus_butler_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: focus_butler_server
        run: serverpod generate

      - name: Run tests
        working-directory: focus_butler_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: focus_butler_server
        run: docker compose down -v
